show_preview_links: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

brand_name: "Ngajikeun.id"
logo_url: /images/logo/logo-ngk.png
display_url: "https://ngajikeun.id"

backend:
  name: git-gateway
  branch: main

links:
  - { label: "📈 Statistik Pengunjung", url: "https://cloud.umami.is/share/wwTd9VfrO2Xe8A77", target: "_blank" }

media_folder: "public/images/uploads"
public_folder: "/public/images/uploads"

collections:
  - name: "dashboard"
    label: "🏠 Dashboard & Statistik"
    files:
      - file: "content/dashboard.json"
        label: "Welcome & Link Statistik"
        name: "main_dashboard"
        fields:
          - {label: "Mode Perawatan (Maintenance)", name: "is_maintenance", widget: "boolean", default: false, hint: "Aktifkan untuk halaman maintenance"}
          - {label: "Pesan Selamat Datang", name: "welcome_msg", widget: "string", default: "Selamat Datang Admin Ngajikeun.id"}
          - {label: "Link Statistik", name: "stats_link", widget: "string", default: "https://cloud.umami.is/share/wwTd9VfrO2Xe8A77", hint: "Link untuk pantau pengunjung"}
          - {label: "Pengaturan Running Text", name: "running_text", widget: "string", default: "Pendaftaran Gelombang Baru Profil Musyrifah Bersanad Telah Dibuka!", hint: "Teks berjalan untuk info/pengumuman."}
          - {label: "Pusat Bantuan", name: "help", widget: "markdown", default: "Hubungi [CiwAI™ Support](https://wa.me/6285121380541)"}

  # --- 1. PROFIL (About) ---
  - name: "about"
    label: "🏢 Tentang Kami"
    files:
      - file: "content/about.json"
        label: "Informasi Detail"
        name: "about_details"
        fields:
          - {label: "Sejarah", name: "history", widget: "markdown"}
          - {label: "Visi", name: "vision", widget: "text"}
          - {label: "Misi", name: "missions", widget: "list", field: {label: "Item", name: "item", widget: "string"}}

          - label: "Galeri Foto"
            name: "slides"
            widget: "list"
            field:
             - { label: "Gambar", name: "image", widget: "image" }

  # --- 2. PROGRAM BELAJAR ---
  - name: "programs"
    label: "📖 Program Belajar"
    folder: "content/programs"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Program Slug", name: "program_slug", widget: "string"}
      - {label: "Buka Pendaftaran", name: "registration_open", widget: "boolean", default: true}
      - {label: "Jenis Program", name: "program_type", widget: "select", options: ["regular", "event", "internal"], default: "regular"}
      - {label: "────────────────────", name: "separator1", widget: "hidden", default: "" }
      - {label: "Title Program", name: "title", widget: "string"}
      - {label: "Memerlukan Approval", name: "requires_approval", widget: "boolean", default: true}
      - {label: "Deskripsi Program", name: "description", widget: "text"}
      - {label: "Link Pendaftaran (WA/Form)", name: "registration_link", widget: "string"}
      - {label: "Image Program", name: "image", widget: "image", required: false}
      - {label: "Detail / Overview Program", name: "body", widget: "markdown", required: false}

  # --- 3. TIM MENTOR ---
  - name: "mentors"
    label: "🎓 Tim Mentor"
    folder: "content/mentors"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Nama Mentor", name: "name", widget: "string"}
      - {label: "Spesialisasi Mentor", name: "specialty", widget: "string"}
      - {label: "Image mentors", name: "image", widget: "image"}
      - {label: "Profil Mentor", name: "bio", widget: "markdown", required: false}

  # --- 4. TESTIMONI ---
  - name: "testimonials"
    label: "💬 Testimoni"
    folder: "content/testimonials"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Nama Testimoni", name: "name", widget: "string"}
      - {label: "Detail Testimoni", name: "content", widget: "text"}

  # --- 5. LITERASI ---
  - name: "articles"
    label: "📰 Artikel"
    folder: "content/articles"
    create: true
    extension: "md"
    fields:
      - {label: "Title Artikel", name: "title", widget: "string"}
      - {label: "Detail Artikel", name: "body", widget: "markdown"}

  # --- 6. PRODUK ---
  - name: "products"
    label: "🛍️ Produk & E-Book"
    folder: "content/products"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Title Produk & E-Book", name: "title", widget: "string"}
      - {label: "Description Produk & E-Book", name: "description", widget: "text"}
      - {label: "Price Produk & E-Book", name: "price", widget: "string"}
      - {label: "Link Produk & E-Book", name: "link", widget: "string"}
      - {label: "Image Produk & E-Book", name: "image", widget: "image", required: false}

  # --- 7. EVALUASI ---
  - name: "quizzes"
    label: "✍️ Koleksi Kuis"
    folder: "content/quizzes"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Title Kuis", name: "title", widget: "string"}
      - {label: "Link Kuis", name: "link", widget: "string"}
